# Global
namespace: emby-subscription
domain: your-example.com

# Backend
backend:
  image: 
    repository: aboogie/emby-backend
    tag: v0.0.0
  replicas: 1
  port: 8000
  env:
    STRIPE_API_KEY: "sk_test_replace"
    STRIPE_WEBHOOK_SECRET: "whsec_replace"
    EMBY_API_KEY: "replace"
    EMBY_SERVER_URL: "http://emby:8096"
    JWT_SECRET_KEY: "replace"
    JWT_ALGORITHM: "HS256"
    JWT_EXPIRATION_MINUTES: "60"
    DATABASE_URL: "sqlite:///./data/subscriptions.db"
    FRONTEND_URL: "http://localhost:5173"
    SMTP_SERVER: "sandbox.smtp.mailtrap.io"
    SMTP_PORT: 587  # usually 587 for TLS, 465 for SSL
    SMTP_USERNAME: "20db3ec6a6b663"
    SMTP_PASSWORD: "83b2f0f6d44ed7"
    FROM_EMAIL: "noreply@yourdomain.com"
  persistence:
    enabled: true
    size: 1Gi
    mountPath: /app/data
    accessModes:
      - ReadWriteOnce
    storageClass: ""  # Use default storage class
    annotations: {}

# Frontend
frontend:
  image: 
    repository: aboogie/emby-frontend
    tag: v0.0.0
  replicas: 1
  port: 5173
  env:
    VITE_API_URL: "http://emby-backend:8000"
    VITE_ALLOWED_HOSTS: "signup.justpurple.org,proxy.justpurple.org"

# Migration
migration:
  enabled: true
  version: ""  # Optional: specify version for unique job names

# Ingress
ingress:
  enabled: true
  host: emby.yourdomain.com
  className: nginx
  annotations: 
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
  tls:
    enabled: false
    secretName: ""
