version: "3.9"
services:
  backend:
    build: ./backend
    container_name: emby-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000

  frontend:
    build: ./frontend

    platform: linux/arm64  
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true # better file watching in Docker
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8000
    depends_on: 
      - backend
    command: npm run dev -- --host 0.0.0.0
