apiVersion: v1
entries:
  emby-subscription:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2025-08-05T09:40:45.4169165Z"
    description: Self-hosted Emby subscription platform with Stripe intergration
    digest: 2d18c934ecd1b1d3ff54e6eefeeaa0dccb8883965939b4b1b3cae7abfde9f9ec
    home: https://github.com/aboogie24/emby_subscription
    keywords:
    - emby
    - stripe
    - subscriptions
    maintainers:
    - email: alfred.brown@alfredbrowniii.io
      name: Alfred Brown
    name: emby-subscription
    sources:
    - https://github.com/aboogie24/emby_subscription
    urls:
    - https://aboogie24.github.io/emby_subscription/charts/emby-subscription-0.1.3.tgz
    version: 0.1.3
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2025-08-05T09:40:45.416669016Z"
    description: Self-hosted Emby subscription platform with Stripe intergration
    digest: d2980111c6614eddfe4365c752ba3526c226f2675b04513aef9d5aba023147c9
    home: https://github.com/aboogie24/emby_subscription
    keywords:
    - emby
    - stripe
    - subscriptions
    maintainers:
    - email: alfred.brown@alfredbrowniii.io
      name: Alfred Brown
    name: emby-subscription
    sources:
    - https://github.com/aboogie24/emby_subscription
    urls:
    - https://aboogie24.github.io/emby_subscription/charts/emby-subscription-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2025-08-05T09:40:45.416428545Z"
    description: Self-hosted Emby subscription platform with Stripe intergration
    digest: a9a3c5ce5f91f495f4551e3b4cd2baa5ca39376477c4b0d0a810776402777e40
    home: https://github.com/aboogie24/emby_subscription
    keywords:
    - emby
    - stripe
    - subscriptions
    maintainers:
    - email: alfred.brown@alfredbrowniii.io
      name: Alfred Brown
    name: emby-subscription
    sources:
    - https://github.com/aboogie24/emby_subscription
    urls:
    - https://aboogie24.github.io/emby_subscription/charts/emby-subscription-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2025-08-05T09:40:45.41615353Z"
    description: Self-hosted Emby subscription platform with Stripe intergration
    digest: 490f0db0602c6f7e22c86733eb8cb80e34d74c622e4bf4587cd84004eb11d7ee
    home: https://github.com/aboogie24/emby_subscription
    keywords:
    - emby
    - stripe
    - subscriptions
    maintainers:
    - email: alfred.brown@alfredbrowniii.io
      name: Alfred Brown
    name: emby-subscription
    sources:
    - https://github.com/aboogie24/emby_subscription
    urls:
    - https://aboogie24.github.io/emby_subscription/charts/emby-subscription-0.1.0.tgz
    version: 0.1.0
generated: "2025-08-05T09:40:45.415755143Z"
