name: Docker and Helm Chart Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  workflow_dispatch:

permissions: 
  contents: write
  packages: write
jobs:
  build-and-push-container:
    runs-on: ubuntu-latest
    environment: Dev
    strategy:
      matrix:
        service: [backend, frontend]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up QEMU (for multi-arch emulation)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./${{ matrix.service }}
          file: ./${{ matrix.service }}/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64 
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/emby-subscription-${{ matrix.service }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/emby-subscription-${{ matrix.service }}:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/emby-subscription-${{ matrix.service }}:${{ github.ref_name }}
      
  helm-release:
    runs-on: ubuntu-latest
    needs: build-and-push-container

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
    
      - name: Extract Version from Tag
        id: vars
        run: |
          VERSION="${GITHUB_REF#refs/tags/}"
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "Chart version will be set to $VERSION"

      - name: Update Chart.yaml with Version
        run: |
          yq e -i ".version = \"${VERSION#v}\"" ./chart/Chart.yaml
          yq e -i ".appVersion = \"${VERSION#v}\"" ./chart/Chart.yaml
          cat ./emby-subscription-chart/Chart.yaml

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.2

      - name: Package Helm chart
        run: |
          helm lint ./chart
          helm package ./chart --destination packaged

      - name: Checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: gh-pages

      - name: Update Helm repo index
        run: |
          cd gh-pages
          mkdir -p charts
          cp ../packaged/*.tgz charts/
          helm repo index charts --url https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/charts --merge charts/index.yaml || helm repo index charts --url https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/charts

      - name: Commit and push to gh-pages
        run: |
          cd gh-pages
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add .
          git commit -m "Update Helm chart [skip ci]" || echo "No changes to commit"
          git push origin gh-pages

    
